### ISSUE TITLE
Think about storing settings in a different format (instead of JSON)

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/opencast-studio#535]
We plan on adding quite a few configuration options still, in particular make a few texts configurable. Large configurations with long texts probably won't look too bad in JSON, making the whole file hard to read. JSON also does not allow comments. So it might be worth thinking about an alternative format. 

YAML was mentioned. I would probably prefer TOML as it's a very minimal format, whereas YAML has a huge grammar and stuff. A simpler and smaller format is better for humans and beneficial as the parsing library will probably be smaller.

Here is an example configuration in different formats:

**JSON**
```json
{
  "opencast": {
    "serverUrl": "/",
    "loginProvided": true
  },
  "upload": {
    "workflowId": "fast"
  },
  "display": {
    "maxFps": 30
  },
  "texts": {
    "uploadSuccessful": {
      "en": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "de": "Loremipsum dolorsit amet, consectetur adipiscingelit, seddo eiusmod tempor incididunt utlabore etdolore magnaaliqua. Utenim ad minim veniam, quis nostrud exercitationullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eufugiat nulla pariatur."
    },
    "firstVisit": {
      "en": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "de": "Loremipsum dolorsit amet, consectetur adipiscingelit, seddo eiusmod tempor incididunt utlabore etdolore magnaaliqua. Utenim ad minim veniam, quis nostrud exercitationullamco laboris nisi ut aliquip ex ea commodo consequat."
    }
  }
}
```

**TOML**
```toml
[opencast]
serverUrl = "/"
loginProvided = true

[upload]
# A comment :)
workflowId = "fast"

[display]
maxFps = 30

[texts.uploadSuccessful]
en = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor 
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis 
nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu 
fugiat nulla pariatur.
"""
de = """
Loremipsum dolorsit amet, consectetur adipiscingelit, seddo eiusmod 
tempor incididunt utlabore etdolore magnaaliqua. Utenim ad minim veniam, quis 
nostrud exercitationullamco laboris nisi ut aliquip ex ea commodo consequat. 
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore 
eufugiat nulla pariatur.
"""

[texts.firstVisit]
# Long single line texts are allowed too, of course
en = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
de = "Loremipsum dolorsit amet, consectetur adipiscingelit, seddo eiusmod tempor incididunt utlabore etdolore magnaaliqua. Utenim ad minim veniam, quis nostrud exercitationullamco laboris nisi ut aliquip ex ea commodo consequat."
```

**YAML**

```yaml
---
# Connection information for Opencast
# Setting these here will disable the settings in the Studio user interface
opencast:

  # URL of where to find Opencast for uploads. 
  # If Studio lives on the same server, a path will do
  serverUrl: "/"

  # If you already logged in to Opencast when you open Studio (e.g. since Studio is included in Opencast).
  # Setting this to false will make Studio ask the user for credentials in its settings.
  # Default: false
  loginProvided: true

# …
upload:
  # The workflow to use for ingests to Opencast
  # Default: studio-upload
  #workflowId: studio-upload

display:
  maxFps: 30

texts:
  uploadSuccessful:
    en: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
      incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
      exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute
      irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur.
    de: Loremipsum dolorsit amet, consectetur adipiscingelit, seddo eiusmod tempor
      incididunt utlabore etdolore magnaaliqua. Utenim ad minim veniam, quis nostrud
      exercitationullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute
      irure dolor in reprehenderit in voluptate velit esse cillum dolore eufugiat
      nulla pariatur.
  firstVisit:
    en: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
      incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
      exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    de: Loremipsum dolorsit amet, consectetur adipiscingelit, seddo eiusmod tempor
      incididunt utlabore etdolore magnaaliqua. Utenim ad minim veniam, quis nostrud
      exercitationullamco laboris nisi ut aliquip ex ea commodo consequat.
```
